version: "3"

services:
  grafana:
    container_name: "chainbase-grafana"
    platform: "linux/amd64"
    build:
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.0.3}
    ports:
      - "3000:3000/tcp"
    volumes:
      - "./dist:/var/lib/grafana/plugins/kallydev-chainbase-datasource"
